---
# tasks file for sparkfabrik.php5
- name: Install packages
  apt: pkg={{ item }} update-cache=yes
  with_items:
    - php5
    - php5-cli
    - php5-curl
    - php5-dev
    - php5-fpm
    - php5-intl
    - php5-mcrypt
    - php5-mysql
  notify:
    - restart php5-fpm

- name: Write basic pool config file
  template: src=etc--php5--fpm--pool.d--www.conf.j2 dest=/etc/php5/fpm/pool.d/www.conf
  sudo: yes
  notify:
    - restart php5-fpm
